// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"gitlab.com/altiano/goreen-tea/src/app"
	"gitlab.com/altiano/goreen-tea/src/domain/assistanceCoordinator"
	"gitlab.com/altiano/goreen-tea/src/domain/customerOrder"
	"gitlab.com/altiano/goreen-tea/src/domain/customerOrder/repo"
	"gitlab.com/altiano/goreen-tea/src/domain/visitorCounter"
	"gitlab.com/altiano/goreen-tea/src/domain/waiter"
	repo2 "gitlab.com/altiano/goreen-tea/src/domain/waiter/repo"
	"gitlab.com/altiano/goreen-tea/src/frameworks"
	"gitlab.com/altiano/goreen-tea/src/frameworks/cli"
	"gitlab.com/altiano/goreen-tea/src/frameworks/database"
	"gitlab.com/altiano/goreen-tea/src/frameworks/email"
	"gitlab.com/altiano/goreen-tea/src/frameworks/memcache"
	"gitlab.com/altiano/goreen-tea/src/frameworks/rest"
	"gitlab.com/altiano/goreen-tea/src/frameworks/trace"
	"gitlab.com/altiano/goreen-tea/src/shared"
)

// Injectors from injectApp.go:

func InjectApp(config shared.Config) app.App {
	manager := trace.NewOtelManager(config)
	emailManager := email.NewManager(config)
	db := database.NewMongoDB(config)
	repoRepo := repo.NewRepo(manager, db)
	domain := customerOrder.NewDomain(manager, emailManager, repoRepo)
	repo3 := repo2.NewRepo(db, manager)
	waiterDomain := waiter.NewDomain(manager, repo3)
	assistanceCoordinatorDomain := assistanceCoordinator.NewDomain(manager, waiterDomain, domain)
	memcacheManager := memcache.NewDummy(config)
	visitorCounterDomain := visitorCounter.NewDomain(manager, memcacheManager)
	appApp := app.NewApp(manager, domain, assistanceCoordinatorDomain, visitorCounterDomain)
	return appApp
}

// Injectors from injectDummyCli.go:

func InjectDummyCLI(config shared.Config, app2 app.App) frameworks.Server {
	server := cli.NewDummyCLI(app2)
	return server
}

// Injectors from injectIris.go:

func InjectIris(config shared.Config, app2 app.App) frameworks.Server {
	manager := trace.NewOtelManager(config)
	server := rest.NewIris(config, manager, app2)
	return server
}
