apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

namePrefix: <app-name>

commonLabels:
  app: <app-name>

images:
  - name: appname-image
    newName: registry.<base-url>/<app-name>